version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: search_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: search
      POSTGRES_USER: search_user
      POSTGRES_PASSWORD: search_pass
    ports: ["${DB_PORT_GATEWAY}:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: search_redis
    restart: unless-stopped
    ports: ["6379:6379"]

volumes:
  pgdata:
